name: US Stock Daily Crawler

on:
  schedule:
    # Run at 8 AM Taiwan time daily (UTC 00:00)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  crawl-and-send:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run stock crawler
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python stock_crawler.py
