name: US Stock Daily Crawler

On:
  schedule:
    - cron: '0 0 * * *
  workflow_dispatch:

jobs:
  crawk:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
     - run: pip -i requirements.txt
    - run: python stock_crawler.py
      env:
            DISCORD_WEBHOOK_URL: $*{ {secrets.DISCORD_WEBHOOKURL}}
